### ISSUE TITLE
ScopeError: A scope on dimension(s) organizer needs to be active for this query

### ISSUE THREAD

**Issue by MEschenbacher** [pretix-unofficial/pretix-newsletter-ml#6]
Pretix version 4.5.0
Plugin pretix-newsletter-ml version 1.3.1

Sending mailinglist subscription mail fails with

```
[2022-02-08 09:21:20,674: INFO/MainProcess] Received task: pretix_newsletter_ml.tasks.newsletter_ml_order_placed[4b7b7f48-c18c-44da-9240-ca6177c931ff]  
[2022-02-08 09:21:20,786: ERROR/ForkPoolWorker-9] Task pretix_newsletter_ml.tasks.newsletter_ml_order_placed[4b7b7f48-c18c-44da-9240-ca6177c931ff] raised unexpected: ScopeError('A scope on dimension(s) organizer needs to be active for this query.')
  File "/usr/opt/pretix/venv/lib/python3.7/site-packages/pretix_newsletter_ml/tasks.py", line 14, in newsletter_ml_order_placed
```

**Comment by raphaelm** [comment]
Yes, this plugin has never been updated to be compatible with more recent pretix versions, since we were not aware of anyone still using it. It's unmaintained from our end (therefore it resides in the `pretix-unofficial` org), if you're interested in sponsoring us to continue maintaining it, feel free to reach out at support@pretix.eu.

**Comment by saschafoerster** [comment]
@MEschenbacher @raphaelm We just wanted to start using it, but found out, that it is not supported anymore. So @MEschenbacher, if this encourages you, here is 1 hoping and waiting user! :)

**Comment by saschafoerster** [comment]
I got this error after trying out in the newest pretix-version: 

```
[2022-07-27 19:23:31,876: ERROR/ForkPoolWorker-3] Task pretix.base.services.orders.perform_order[df3fb439-63cc-4549-a1ed-a0aa199779e1] raised unexpected: TypeError('newsletter_ml_order_placed() takes 2 positional arguments but 3 were given')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/pretix/src/pretix/base/services/tasks.py", line 62, in __call__
    ret = super().__call__(*args, **kwargs)
  File "/pretix/src/pretix/base/services/tasks.py", line 108, in __call__
    ret = super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/pretix/src/pretix/base/services/orders.py", line 2375, in perform_order
    return _perform_order(event, payment_provider, positions, email, locale, address, meta_info,
  File "/pretix/src/pretix/base/services/orders.py", line 1027, in _perform_order
    order, payment = _create_order(event, email, positions, now_dt, pprov,
  File "/pretix/src/pretix/base/services/orders.py", line 926, in _create_order
    order_placed.send(event, order=order)
  File "/pretix/src/pretix/base/signals.py", line 104, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.9/site-packages/pretix_newsletter_ml/signals.py", line 42, in order_placed
    newsletter_ml_order_placed.apply_async(args=(sender.pk, order.pk))
  File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 531, in apply_async
    check_arguments(*(args or ()), **(kwargs or {}))
TypeError: newsletter_ml_order_placed() takes 2 positional arguments but 3 were given
```

**Comment by MEschenbacher** [comment]
Thank you for the report. I've prepared another PR which fixes the regression.
